import { BankTransferInfoDto } from "./BankTransferInfoDto";
import { LanguageListDto } from "./LanguageListDto";

export class ErpECollectionReviewDto {
    recId: string = '';
    propertyId: string = '';
    amount: number = 0;
    eMail?: string | null;
    paid?: boolean;
    payeeNote?: string | null;
    cancel?: boolean;
    refCode?: string | null;
    eCollectionPacketType?: number;
    eCollectionType?: number;
    cardInfo?: string | null;
    rate?: number;
    eCollectionInfo?: string | null;
    templateOwnerId?: string | null;
    paymentInfo?: string | null;
    fullName?: string | null;
    discountAmount?: number;
    discountRatio?: number;
    promotionCode?: string | null;
    endDate?: Date;
    createdDate?: string;
    virtualPosId?: string | null;
    isRefund?: boolean;
    paymentType?: number;
    selectedVirtualPosId: string = '';
    selectedLanguageCode?: string | null;
    undoInstallment?: boolean;
    eCollectionEndType?: number;
    endTime?: string | null;
    sectionCodeId?: string | null;
    deleted?: boolean;
    successFailResponse?: string | null;
    currentcode?: string;
    currentremark?: string;
    amountByBank?: number;
    currentRecid?: string | null;
    id?: number;
    reservationId?: string | null;
    sberbankOrderId?: string;
    sberbankOrderNumber?: string;
    paidDate?: Date;
    paymentLink?: string | null;
    currencyId: string = '';
    currencyName?: string;
    // recordEMail: string;
    // paidDate: Date;
    // connectedRecords: string;
    symbol?: string;
    images?: string;
    favimageurl?: string;
    companyFaviconUrl?: string;
    code: string = '';
    commissionByBank?: number;
    nameSurname?: string;
    saleDate?: Date;
    checkInDate?: Date;
    checkOutDate?: Date;
    adult?: number;
    child?: number;
    reservation?: boolean;
    voucher?: string;
    installment?: string;
    currencyByBank?: string;
    currencyByBankName?: string;
    createdBy?: string;
    manageAccountAmount: boolean = false;
    awardPermissionName?: string;
    title?: string;
    titleList: LanguageListDto[] = [];
    bankCommission?: string;
    reservationDetailId?: string;
    refundAmount?: number;
    bankTransferList: BankTransferInfoDto[] = [];
    preWriting?: string;
    preWritingList: LanguageListDto[] = [];
    accountHolder?: string;
    accountHolderList: LanguageListDto[] = [];
    maleControlRemark?: string;
    maleControlRemarkList: LanguageListDto[] = [];
}
