export class PmsECollectionByIdForReservationDto {
    recId?: string;
    amount?: number;
    currencyid?: string | null;
    eMail?: string;
    rate?: number;
    paid?: boolean;
    payeeNote?: string;
    cancel?: boolean;
    refCode?: string;
    eCollectionPacketType?: number;
    paidDate?: string | null;
    endDate?: string | null;
    eCollectionType?: number;
    eCollectionInfo?: string;
    connectedRecords?: string;
    paymentInfo?: string;
    fullName?: string;
    discountAmount?: number;
    discountRatio?: number;
    virtualPosId?: string;
    isRefund?: boolean;
    paymentType?: number;
    selectedVirtualPosId?: string;
    selectedLanguageCode?: string;
    undoInstallment?: boolean;
    eCollectionEndType?: number;
    endTime?: string;
    symbol?: string;
    favimageurl?: string;
    code?: string;
    successFailResponse?: string | null;
    feedbackMails?: string | null;
    offerandReservationMails?: string | null;
    amountByBank?: number | null;
    voucher?: string;
    currencyCode?: string;
    enterprisesId?: string | null;
    propertyId?: string | null;
    paymentLink?: string | null;
}
